---
repos:
  # id can either be an exact repo ID or a regex.
  # If using a regex, it must start and end with a slash.
  # Repo ID's are of the form {VCS hostname}/{org}/{repo name}, ex.
  # github.com/runatlantis/atlantis.
  - id: git.ednz.fr/ednz-cloud/nomad-deployments
    branch: /.*/
    workflow: opentofu
    allowed_overrides: ["pre_workflow_hooks", "post_workflow_hooks"]

workflows:
  opentofu:
    plan:
      steps:
        - run: rm -rf .terraform
        - run: /usr/local/bin/tofu init -reconfigure
        - run: /usr/local/bin/tofu plan
    apply:
      steps:
        - run: rm -rf .terraform
        - run: /usr/local/bin/tofu init
        - run: /usr/local/bin/tofu apply -auto-approve
