---
repos:
  # id can either be an exact repo ID or a regex.
  # If using a regex, it must start and end with a slash.
  # Repo ID's are of the form {VCS hostname}/{org}/{repo name}, ex.
  # github.com/runatlantis/atlantis.
  - id: git.ednz.fr/ednz-cloud/nomad-deployments
    branch: /.*/
    workflow: opentofu
    pre_workflow_hooks:
      - run: |
          export NOMAD_TOKEN=$(curl --silent --header "X-Vault-Token: $VAULT_TOKEN" https://vault.ednz.fr/v1/nomad/creds/full-access | grep -o '"secret_id":"[^"]*' | sed 's/"secret_id":"//')
          export CONSUL_HTTP_TOKEN=$(curl --silent --header "X-Vault-Token: $VAULT_TOKEN" https://vault.ednz.fr/v1/consul/creds/admins | grep -o '"token":"[^"]*' | sed 's/"token":"//')
    post_workflow_hooks:
      - run: |
          unset NOMAD_TOKEN
          unset CONSUL_HTTP_TOKEN

workflows:
  opentofu:
    plan:
      steps:
        - run: rm -rf .terraform
        - run: /usr/local/bin/tofu init -reconfigure
        - run: /usr/local/bin/tofu plan
    apply:
      steps:
        - run: rm -rf .terraform
        - run: /usr/local/bin/tofu init
        - run: /usr/local/bin/tofu apply -auto-approve
