---
name: deploy-stacks
on:
  push:
    branches:
      - main
    paths:
      - "!.gitea/**"
      - "!_**"

env:
  IMAGE_NAME: ${{ gitea.repository }}
  BUILD_PLATFORMS: linux/amd64

jobs:
  deploy:
    name: Deploy nomad jobs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y curl jq

          curl https://vault.ednz.fr/v1/ednz-root-ca/ca -o /tmp/ednz_ca
          openssl x509 -inform DER -in /tmp/ednz_ca -out /usr/local/share/ca-certificates/ednz_ca.crt -outform pem
          update-ca-certificates

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      - name: Get secrets from vault
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: "https://vault.ednz.fr"
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          secrets: |
            kv/data/cicd/vault/infrabuilder approle_id | VAULT_INFRABUILDER_APPROLE_ID ;
            kv/data/cicd/vault/infrabuilder approle_secret_id | VAULT_INFRABUILDER_APPROLE_SECRET_ID ;
            kv/data/applications/gitea/users/actions username | GITEA_REGISTRY_USERNAME ;
            kv/data/applications/gitea/users/actions token_read | GITEA_REGISTRY_TOKEN ;

      - name: Get required credentials
        id: tofu-auth
        run: |
          VAULT_TOKEN=$(curl --silent --request POST --data '{"role_id": "${{ steps.import-secrets.outputs.VAULT_INFRABUILDER_APPROLE_ID }}","secret_id": "${{ steps.import-secrets.outputs.VAULT_INFRABUILDER_APPROLE_SECRET_ID }}"}' https://vault.ednz.fr/v1/auth/approle/login | jq -r .auth.client_token)
          NOMAD_TOKEN=$(curl --silent --header "X-Vault-Token: $VAULT_TOKEN" https://vault.ednz.fr/v1/nomad/creds/full-access | jq -r .data.secret_id)
          CONSUL_TOKEN=$(curl --silent --header "X-Vault-Token: $VAULT_TOKEN" https://vault.ednz.fr/v1/consul/creds/admins | jq -r .data.token)

          git config --global url."https://${{ steps.import-secrets.outputs.GITEA_REGISTRY_USERNAME }}:${{ steps.import-secrets.outputs.GITEA_REGISTRY_TOKEN }}@git.ednz.fr".insteadOf https://git.ednz.fr

          echo "vault_token=$VAULT_TOKEN" >> $GITHUB_OUTPUT
          echo "nomad_token=$NOMAD_TOKEN" >> $GITHUB_OUTPUT
          echo "consul_token=$CONSUL_TOKEN" >> $GITHUB_OUTPUT

      - name: Tofu init
        run: tofu init
        shell: bash
        working-directory: ./terraform/${{ gitea.ref_type == 'branch' && 'devel' || 'production' }}
        env:
          CONSUL_HTTP_TOKEN: ${{ steps.tofu-auth.outputs.consul_token }}

      - name: Tofu plan
        run: tofu plan${{ gitea.ref_type == 'branch' && ' -replace module.nomad_job.nomad_job.this[\"website\"]' || '' }} -out=plan.tfplan
        shell: bash
        working-directory: ./terraform/${{ gitea.ref_type == 'branch' && 'devel' || 'production' }}
        env:
          NOMAD_TOKEN: ${{ steps.tofu-auth.outputs.nomad_token }}
          VAULT_TOKEN: ${{ steps.tofu-auth.outputs.vault_token }}
          CONSUL_HTTP_TOKEN: ${{ steps.tofu-auth.outputs.consul_token }}

      - name: Tofu apply
        run: tofu apply plan.tfplan
        shell: bash
        working-directory: ./terraform/${{ gitea.ref_type == 'branch' && 'devel' || 'production' }}
        env:
          NOMAD_TOKEN: ${{ steps.tofu-auth.outputs.nomad_token }}
          VAULT_TOKEN: ${{ steps.tofu-auth.outputs.vault_token }}
          CONSUL_HTTP_TOKEN: ${{ steps.tofu-auth.outputs.consul_token }}

      - name: Expire credentials
        run: |
          curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST https://vault.ednz.fr/v1/auth/token/revoke-self
        env:
          VAULT_TOKEN: ${{ steps.tofu-auth.outputs.vault_token }}
