---
name: pull-requests-open
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
    paths:
      - "!.gitea/**"
      - "!_**"

env:
  IMAGE_NAME: ${{ gitea.repository }}
  BUILD_PLATFORMS: linux/amd64

jobs:
  plan:
    name: Plan nomad jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install required packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y curl jq

          curl https://vault.ednz.fr/v1/ednz-root-ca/ca -o /tmp/ednz_ca
          openssl x509 -inform DER -in /tmp/ednz_ca -out /usr/local/share/ca-certificates/ednz_ca.crt -outform pem
          update-ca-certificates

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      - name: Get secrets from vault
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: "https://vault.ednz.fr"
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          secrets: |
            kv/data/cicd/vault/infrabuilder approle_id | VAULT_INFRABUILDER_APPROLE_ID ;
            kv/data/cicd/vault/infrabuilder approle_secret_id | VAULT_INFRABUILDER_APPROLE_SECRET_ID ;
            kv/data/applications/gitea/users/actions username | GITEA_REGISTRY_USERNAME ;
            kv/data/applications/gitea/users/actions token_read | GITEA_REGISTRY_TOKEN ;

      - name: Get required credentials
        id: tofu-auth
        run: |
          VAULT_TOKEN=$(curl --silent --request POST --data '{"role_id": "${{ steps.import-secrets.outputs.VAULT_INFRABUILDER_APPROLE_ID }}","secret_id": "${{ steps.import-secrets.outputs.VAULT_INFRABUILDER_APPROLE_SECRET_ID }}"}' https://vault.ednz.fr/v1/auth/approle/login | jq -r .auth.client_token)
          NOMAD_TOKEN=$(curl --silent --header "X-Vault-Token: $VAULT_TOKEN" https://vault.ednz.fr/v1/nomad/creds/full-access | jq -r .data.secret_id)
          CONSUL_TOKEN=$(curl --silent --header "X-Vault-Token: $VAULT_TOKEN" https://vault.ednz.fr/v1/consul/creds/admins | jq -r .data.token)

          git config --global url."https://${{ steps.import-secrets.outputs.GITEA_REGISTRY_USERNAME }}:${{ steps.import-secrets.outputs.GITEA_REGISTRY_TOKEN }}@git.ednz.fr".insteadOf https://git.ednz.fr

          echo "vault_token=$VAULT_TOKEN" >> $GITHUB_OUTPUT
          echo "nomad_token=$NOMAD_TOKEN" >> $GITHUB_OUTPUT
          echo "consul_token=$CONSUL_TOKEN" >> $GITHUB_OUTPUT

      - name: Install python dependencies
        run: python3 -m pip install -r ${{ gitea.workspace }}/.gitea/scripts/requirements.txt
        shell: bash
        working-directory: ${{ gitea.workspace }}

      - name: Plan all changed stacks
        run: python3 .gitea/scripts/deploy_stacks.py --plan-only
        shell: bash
        working-directory: ${{ gitea.workspace }}
        env:
          NOMAD_TOKEN: ${{ steps.tofu-auth.outputs.nomad_token }}
          VAULT_TOKEN: ${{ steps.tofu-auth.outputs.vault_token }}
          CONSUL_HTTP_TOKEN: ${{ steps.tofu-auth.outputs.consul_token }}
