identity_providers:
  oidc:
    hmac_secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.oidc_hmac_secret}}{{end}}'
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
    clients:
      ## Gitea OAuth
      - id: gitea
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.gitea_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - email
          - profile
          - groups
        redirect_uris:
          - https://git.ednz.fr/user/oauth2/authelia/callback
        userinfo_signing_algorithm: none
      ## Wikijs OAuth
      - id: wikijs
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.wikijs_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - email
        redirect_uris:
          - https://wiki.ednz.fr/login/0d7f2baf-a6da-4f14-b85c-44e2894c7557/callback
        userinfo_signing_algorithm: none
        response_modes:
          - form_post
      ## Vikunja OAuth
      - id: vikunja
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.vikunja_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - email
        redirect_uris:
          - https://vik.ednz.fr/auth/openid/authelia
        userinfo_signing_algorithm: none
      ## Nomad OAuth
      - id: nomad
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.nomad_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - groups
        redirect_uris:
          - http://localhost:4649/oidc/callback
          - https://nomad.ednz.fr/ui/settings/tokens
        userinfo_signing_algorithm: none
      ## Vault OAuth
      - id: vault
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.vault_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - http://localhost:8250/oidc/callback
          - https://vault.ednz.fr/ui/vault/auth/authelia/oidc/callback
        userinfo_signing_algorithm: none
      ## Openstack OAuth
      - id: openstack
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.openstack_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - https://openstack.ednz.fr:5000/v3/auth/OS-FEDERATION/identity_providers/authelia/protocols/openid/websso
          - https://openstack.ednz.fr:5000/redirect_uri
          - https://os-vip.ednz.fr:5000/v3/auth/OS-FEDERATION/identity_providers/authelia/protocols/openid/websso
          - https://os-vip.ednz.fr:5000/redirect_uri
        response_types:
          - id_token
        grant_types:
          - implicit
        userinfo_signing_algorithm: none
      ## Headscale OAuth
      - id: headscale
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.headscale_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - email
          - groups
        redirect_uris:
          - https://vpn.ednz.fr/oidc/callback
        userinfo_signing_algorithm: none
        grant_types:
          - implicit
          - authorization_code
      ## Headscale WebUI OAuth
      - id: headscale-webui
        secret: '{{with secret "kv_hs/hashistack/nomad/services/authelia"}}{{.Data.data.headscale_webui_secret}}{{end}}'
        public: false
        consent_mode: pre-configured
        pre_configured_consent_duration: 1w
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - email
        redirect_uris:
          - https://remote.ednz.fr/ui/oidc_callback
        userinfo_signing_algorithm: none
